ingestion_interval: day
sources:
  - data_object: PRODUCTS
    source_type: local
    path: /opt/bitnami/spark/postman-assignment/source_data/products.csv
    options: header='True', inferSchema='True', delimiter=',',multiLine='True'
    format: csv